version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  pre_build:
    commands:
      - python3.12 -m venv ~/.venv
      - . ~/.venv/bin/activate
      - pip install --upgrade pip && pip install -r requirements.txt
      - pylint --disable=R,C calculator.py
      - python -m pytest -vv --cov=calculator test_calculator.py
      - black *.py