version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  pre_build:
    commands:
      - python3.12 -m venv ~/.venv
      - ~/.venv/bin/python -m pip install --upgrade pip
      - ~/.venv/bin/python -m pip install -r requirements.txt
      - ~/.venv/bin/python -m pylint --disable=R,C calculator.py
      - ~/.venv/bin/python -m pytest -vv --cov=calculator test_calculator.py
      - ~/.venv/bin/python -m black --check *.py